(if (= (len args) 0)
    (player:tell "Syntax: @verb obj:new-verb-name")
    (let ((raw-parse ($verbutils:parse-verbstr-plumbing argstr))
          (result-code (get raw-parse 0)))
      (cond
       ((= result-code 1)
        (player:tell "Invalid verb string. Use \"obj:verb\""))
       ((= result-code 2)
        (player:tell "The object you specified was not found."))
       ((= result-code 4)
        (player:tell "Malformed argspec. Example: (any,to,this)"))
       ((= result-code 5)
        (player:tell "Invalid argspec: " (get raw-parse 5)))
       ((let ((obj-defined-on (get raw-parse 1))
              (obj (get raw-parse 3))
              (verb-ref (get raw-parse 4))
              (arg-spec (get raw-parse 5)))
          (do
           (if (= result-code 0)
               (if (= obj-defined-on obj)
                   (player:tell "Warning: " ($o obj) "already defines"
                                "a verb with that name")
                   0)
               0)
           (addverb obj verb-ref)
           (if (nil? arg-spec)
               0
               (setverbargs obj verb-ref arg-spec))
           (echo "Added verb called \"" verb-ref "\" to " ($o obj))))))))
